import base64
from typing import cast
from openai import AsyncOpenAI
from openai.types.responses import ResponseInputParam, ToolParam

from config import OPENAI_API_KEY

# Initialize the AsyncOpenAI client
openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)

async def generate_thumbnail(prompt: str, style_prompt: str, headshot_url: str) -> bytes:
    """
    Use the Responses API with gpt-image-2 as a built-in image_generation tool.
    Pass the headshot URL directly as an input_image.
    Returns raw PNG bytes.
    """
    full_prompt = (
        f"{style_prompt}\n\n"
        f"user request: {prompt}\n\n"
        "IMPORTANT: The generated thumbnail MUST prominently feature the person "
        "shown in the provided reference headshot photo. Keep their likeness accurate."
    )

    # 1. We swap the undefined 'client' with 'openai_client'
    # 2. We use the correct plural 'responses.create' method
    # 3. We pass stream=False to ensure we get a Response object (non-streaming)
    #    instead of an AsyncStream, avoiding the "AsyncStream has no attribute output" error.
    # 4. We fix the text input part type to "input_text" (not "text").
    # 5. We use typing.cast to satisfy Pyright static typing checks for input and tools.
    response = await openai_client.responses.create(
        model="gpt",
        stream=False,
        input=cast(ResponseInputParam, [
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": full_prompt},
                    {"type": "input_image", "image_url": headshot_url}
                ]
            }
        ]),
        tools=[cast(ToolParam, {
            "type": "image_generation",
            "model": "gpt-image-2",
            "size": "1536x1024",
            "quality": "high",
            "output_format": "png"
        })]
    )

    # Extract and decode the base64-encoded generated image from the tool output
    image_base64 = ""
    for output in response.output:
        if output.type == "image_generation_call" and output.result:
            image_base64 = output.result
            break

    if not image_base64:
        raise ValueError("No image was generated by the OpenAI Responses API.")

    return base64.b64decode(image_base64)
